### PR TITLE
added api server

### PR DESCRIPTION
**Pull request by obedm503**
to test:
 make sure you have yarn installed globally
```
npm install -g yarn
```

then run
```
yarn install
```
to kick off the server
```
yarn run api
```
navigate to `localhost:3000/api/017770` and you should see some json object

### CODE REVIEW

**Comment by glacay30** [comment]
I followed the steps (installed node.js and npm successfully, installed yarn globally, installed yarn) but trying to do the command `yarn run api` failed.
It gave me this [error](https://gyazo.com/ee055240343cf24c2caf3e10c65ae259).

**Comment by glacay30** [comment]
I got it working by 
`npm install -g json-server`
Now I can successfully browse the db.json by going to my browser and typing `localhost:3000` into the search bar.

At least in the meanwhile, this provides a handy way to control the system so that we don't have to break anything important and test different scenarios. Nice job! 

I think creating a new branch or keeping this branch might be better than merging, that way we can still use the api without touching the main program that will use Star's. Does that sound good?

**Comment by obedm503** [comment]
the mock is supposed to help you start development until star gives the api. this way @Hellsing76 can start figuring out the logic. I would suggest abstracting the api logic into some other module/file to make it easier when the actual api comes along. so yes I suggest you merge it.

Also I know you're not using javascript but i suggest, if you do need some npm package, you install it using yarn. it is alot faster

**Comment by glacay30** [comment]
In that case, @Hellsing76 should be the one to setup the API system so that he can use the scanner in the meanwhile. And yes, it should be in a separate python file to keep the API communication separate (as in different functions that communicate with different APIs that we have, such as the username-password one we're using right now, the new mock API, and eventually the future API)

I'll work on separating the API communication from the main.py and creating a better GUI in the meanwhile.

**Pull request merged**
